version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - postgres_db
  frontend:
    build: ./frontend
    ports:
      - "80:80"
  postgres_db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: nest_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
