services:
  backend:
    build: ./backend
    ports:
      - 4000:4000
    depends_on:
      - postgres_db
    networks:
      - gallerybook
  frontend:
    build: ./frontend
    ports:
      - 80:80
    networks:
      - gallerybook
  postgres_db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: nest_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports: 
      - 5434:5432
    networks:
      - gallerybook
  test_db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: nest_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    ports: 
      - 5435:5432
    networks:
      - gallerybook

volumes:
  postgres_data:
  postgres_test_data:
networks:
  gallerybook:
